apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: vestify-dev
manifests:
  rawYaml:
    - ./infra/k8s/*
portForward:
  - resourceType: service
    resourceName: rabbitmq-srv
    namespace: default
    port: 15672
    localPort: 15672
build:
  local:
    push: false
  artifacts:
    - image: user-service
      context: ./user-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.*"
            dest: .
    - image: product-service
      context: ./product-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.*"
            dest: .
    - image: order-service
      context: ./order-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.*"
            dest: .
    - image: job-service
      context: ./jobs-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.*"
            dest: .
    - image: payment-service
      context: ./payment-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.*"
            dest: .
    - image: client
      context: ./frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.*"
            dest: /app

